version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c "sleep 5 && python3 manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
